stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
    - cd ~
    - wget -O /tmp/apache-maven.tar.gz https://downloads.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz

    - tar xf /tmp/apache-maven.tar.gz -C /opt

    - export M2_HOME=/opt/apache-maven-3.8.5
    - export PATH=${M2_HOME}/bin:${PATH}
    - mvn clean 
    - mvn package
  dependencies:
    - test-job

test-job:
  stage: test
  script:
    - echo "Running test job"
    - echo "This is a test job to verify the GitLab CI Runner setup"
    - echo "Add your test commands here"
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying the application done"
  dependencies:
    - build
