stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
    - mvn --version
    - java -version
    - mvn dependency:purge-local-repository
    - mvn dependency:purge-local-repository -U
    - mvn
  dependencies:
    - test-job

test-job:
  stage: test
  script:
    - echo "Running test job"
    - echo "This is a test job to verify the GitLab CI Runner setup"
    - echo "Add your test commands here"
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying the application done"
  dependencies:
    - build
