stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
    - tar xzvf apache-maven-3.9.6-bin.tar.gz
    - mv apache-maven-3.9.6 /desired/path
    - export M2_HOME=/desired/path/apache-maven-3.9.6
    - export PATH=$M2_HOME/bin:$PATH
    - mvn --version
    - java -version
    - mvn dependency:purge-local-repository
    - mvn dependency:purge-local-repository -U
    - mvn
  dependencies:
    - test-job

test-job:
  stage: test
  script:
    - echo "Running test job"
    - echo "This is a test job to verify the GitLab CI Runner setup"
    - echo "Add your test commands here"
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying the application done"
  dependencies:
    - build
